// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class WardData : MonoBehaviour
{
	public class Row
	{
		public string WardNumber;
		public string HouseholdNum;
		public string UniverstiyDegree;
		public string Employed;
	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.WardNumber = grid[i][0];
			row.HouseholdNum = grid[i][1];
			row.UniverstiyDegree = grid[i][2];
			row.Employed = grid[i][3];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_WardNumber(string find)
	{
		return rowList.Find(x => x.WardNumber == find);
	}
	public List<Row> FindAll_WardNumber(string find)
	{
		return rowList.FindAll(x => x.WardNumber == find);
	}
	public Row Find_HouseholdNum(string find)
	{
		return rowList.Find(x => x.HouseholdNum == find);
	}
	public List<Row> FindAll_HouseholdNum(string find)
	{
		return rowList.FindAll(x => x.HouseholdNum == find);
	}
	public Row Find_UniverstiyDegree(string find)
	{
		return rowList.Find(x => x.UniverstiyDegree == find);
	}
	public List<Row> FindAll_UniverstiyDegree(string find)
	{
		return rowList.FindAll(x => x.UniverstiyDegree == find);
	}
	public Row Find_Employed(string find)
	{
		return rowList.Find(x => x.Employed == find);
	}
	public List<Row> FindAll_Employed(string find)
	{
		return rowList.FindAll(x => x.Employed == find);
	}

}